name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install LLVM
        shell: pwsh
        run: |
          $zipUrl = "https://github.com/romch007/llvm-win-build/releases/download/21.1.8/LLVM-21.1.8-msvc-x64.zip"
          $zipPath  = "$env:RUNNER_TEMP\llvm.zip"
          $destPath = "C:\LLVM"

          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath

          if (Test-Path $destPath) {
            Remove-Item $destPath -Recurse -Force
          }

          Expand-Archive -Path $zipPath -DestinationPath $destPath -Force

          "C:\LLVM\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build floc
        shell: pwsh
        run: |
          cargo build --release --bin=floc
